Repository chingu-voyages/v11-bears-team-08, pull requests merged in 2019-10, with the labels that each got.

#30 Feature/front messaging page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Chat/index.js
  client/src/components/Message/index.js
  client/src/components/MessageInput/index.js
  client/src/components/Messages/index.js
  client/src/pages/Conversation/index.js
  src/resources/components/user/user.model.js
Labels: design, frontend

#38 fix deployment failing because faker is used on actual code
  client/package-lock.json
  client/package.json
Labels: bug

#32 [ready] auth frontend API
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/lib/Flex/index.js
  client/src/index.js
  client/src/services/api.js
Labels: frontend

#42 Refactor/auth frontend
  client/src/App.js
  client/src/components/Chat/index.js
  client/src/components/MessageInput/index.js
  client/src/components/Nav/index.js
  client/src/components/Search/index.js
  client/src/pages/Conversation/index.js
  client/src/pages/Landing/index.js
Labels: bug, frontend, refactor

#41 Refactor auth backend
  index.js
  package-lock.json
  package.json
  src/resources/components/user/user.model.js
  src/utils/auth.js
Labels: backend, bug, refactor

#43 authentication front end
  client/src/App.js
  client/src/Global.js
  client/src/assets/img/register.jpg
  client/src/assets/img/touch.jpg
  client/src/pages/Signin/index.js
  client/src/pages/Signup/index.js
  src/utils/auth.js
Labels: frontend
