Repository chingu-voyages/v11-bears-team-08, pull requests merged in 2019-09, with the labels that each got.

#15 Bug/jest configuration
  client/package-lock.json
  client/package.json
  jest.config.js
Labels: bug, configuration

#18 [WiP]Feature/signup module
  index.js
  package-lock.json
  package.json
  src/controllers/example.test.js
  src/index.router.js
  src/resources/components/user/user.controllers.js
  src/resources/components/user/user.model.js
  src/resources/components/user/user.router.js
  src/routes/example.test.js
  src/utils/__tests__/auth.js
  src/utils/auth.js
Labels: backend, help wanted

#29 Trainer & client account creation
  src/resources/components/client/client.model.js
  src/resources/components/trainer/trainer.model.js
  src/resources/components/user/user.model.js
  src/utils/auth.js
Labels: Epic, backend, documentation
